version: "2"

services:
  night-owl:
    image: github.com/tesarwijaya/night-owl:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: dockerfiles/app.docker
    container_name: "night-owl"
    working_dir: /usr/src/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on: 
      - night-owl-sql

  night-owl-sql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${APP_SQL_DB_PASSWORD}"
      POSTGRES_USER: "${APP_SQL_DB_USERNAME}"
      POSTGRES_DB: "${APP_SQL_DB_NAME}"
    ports:
      - "${APP_SQL_DB_PORT}:${APP_SQL_DB_PORT}"

networks:
  default:
    external: 
      name: night-owl-bridge
    driver: bridge